### ISSUE TITLE
Won't build with #define CANOPEN_MASTER 0

### ISSUE THREAD

**Issue by cajt** [DroidDrive/lely_modm_example#2]
The master example build finishes with an binary.
Trying to build the associated slave (by setting _#define CANOPEN_MASTER 0_) quits with the following error message:

In file included from main.cpp:40:
./include/canopen/Slave.hpp:9:10: fatal error: include/canopen/cia402/CiA402Driver.hpp: No such file or directory
    9 | #include <include/canopen/cia402/CiA402Driver.hpp>

**Comment by kikass13** [comment]
@cajt 
sorry, when refactoring the code I have messed up the Header name :)

should be fixed now 
 * git pull origin master --ff

at least it compiles / works properly on my boards :+1:

**Comment by cajt** [comment]
Works on my machine too, at least the compilation, the hw setup is missing at the moment. Thanks a lot :-)

**Comment by kikass13** [comment]
@cajt what do you intend to use, if I may ask that question (out of interest) :)

**Comment by cajt** [comment]
I would like build an evaluation-setup for different CAN-based protocols, the other candidate being UAVCAN.

**Comment by kikass13** [comment]
Oh, the uavcan thing sounds interesting :) are you making this public ? I would certainly want to take good look at that  :)

**Comment by cajt** [comment]
Its a side project, it might not look pretty and take a long time to complete, but there are no substantial reasons against publication.
